export const eng = {
  authorisation:'Authorisation',
  email:'Email',
  password:'Password',
  enter:'Log in',
  dontHaveAccount:"Don't have account?",
  signUp:'Sign up',
  registration:'Registration',
  nickName:'Nickname',
  passConfirm:'Password confirmation',
  soonInCinema:'Soon in cinema',
  premiers:"Premiers",
  nowWatching:'Now Watching',
  seeAll:'see all',
  recommendations:'Recommendation',
  myLists:'My lists',
  favorite:'Favorite',
  nameMustHave5Sym:'The name must have at least 5 characters',
  close:'Close',
  enterName:'Enter name...',
  save:'Save',
  film:'Film',
  films:'Film',
  serial:'Serial',
  serials:'Serials',
  listsNotFound:'Lists not found',
  novelty:'Novelty',
  bestSerials:'Best serials',
  searchPlh:'Search...',
  search:'Search',
  actor:'Actor',
  chooseYear:'Choose Year',
  chooseGenre:'Choose Genre',
  reset:'Reset',
  writeComment:'Write comment',
  add:'Add',
  addTo:'Add to',
  main:'Main page',
  profile:'Profile',
  bestFilms:'Best films',
  lightTheme:'Light',
  darkTheme:'Dark',
  notificationNotFound:'Notifications not found',
  allNotifications:'All notifications',
  trailer:'Trailer',
  hide:'Hide',
  ratings:'Ratings',
  team:'Team',
  details:'Details',
  genres:'Genres',
  reviews:'Reviews',
  allReviews:'All reviews',
  cast:'Cast',
  directors:'Directors and screenwriters',
  budget:'Budget',
  studios:'Studios',
  countries:'Countries',
  originalLanguage:'Original Language',
  speakLanguage:'Speak Language',
  similarSerials:'Similar Serials',
  similarFilms:'Similar Films',
  homePage:'Home page',
  seasons:'Seasons',
  episodes:'Episodes',
  asKnownAs:'Also known as',
  birthday:'Birthday Date',
  birthdayPlace:'Birthday Place',
  biography:'Biography',
  rename:'Rename',
  areYouSure:'Are you sure?',
  deleteWatchList:'Delete watchlist',
  noCancel:'No, cancel',
  deleting:'Deleting...',
  yesDelete:'Yes, delete it',
  success:'Success',
  chooseFavoriteActors:'Choose favorite actors',
  chooseFavoriteGenres:'Choose favorite genres',
  recentActivity:'Recent Activity',
  exit:'Exit',
  subscribersNotFound:'Subscribers not found',
  subscriptionsNotFound:'Subscriptions not found',
  filmsNotFound:'Films not found',
  subscribers:'Subscribers',
  subscriptions:'Subscriptions',
  lists:'Lists',
  newList:'New List',
  favorites:'Favorites',
  notifications:'Notifications',
  sortBy:"Sort by",
  asc:'ASC',
  desc:'DESC',
  ratingHighest:'Rating Highest',
  ratingLowest:'Rating Lowest',
  all:'All',
  successReg:'Success registration',
  successAddList:'List created!',
  subscriber:'Subscribed',
  subscribe:'Subscribed'
}
export const ukr = {
  authorisation:'Авторизація',
  email:'Пошта',
  password:'Пароль',
  enter:'Увійти',
  dontHaveAccount:'Не маєте акаунту?',
  signUp:'Зареєструватись',
  registration:'Реєстрація',
  nickName:'Нікнейм',
  passConfirm:'Підтвердження паролю',
  soonInCinema:'Скоро у кіно!',
  premiers:"Прем\'єри",
  nowWatching:'Зараз дивляться',
  seeAll:'Див.Все',
  recommendations:'Рекомендації',
  myLists:'Мої Списки',
  favorite:'Улюблені',
  nameMustHave5Sym:'Назва повинна мати мінімум 5 символів',
  close:'Закрити',
  enterName:'Введіть назву...',
  save:'Зберегти',
  film:'Фільм',
  films:'Фільми',
  serial:'Серіал',
  serials:'Серіали',
  listsNotFound:'Списків не знайдено',
  novelty:'Новинки',
  bestSerials:'Кращі серіали',
  searchPlh:'Пошук...',
  search:'Пошук',
  actor:'Актор',
  chooseYear:'Оберіть рік',
  chooseGenre:'Оберіть жанр',
  reset:'Скинути',
  writeComment:'Напишіть коментар',
  add:'Додати',
  addTo:'Додати до',
  main:"Головна",
  profile:"Профіль",
  bestFilms:"Кращі фільми",
  lightTheme:'Світла',
  darkTheme:'Темна',
  notificationNotFound:'Немає повідомлень',
  allNotifications:'Усі повідомлення',
  trailer:'Трейлер',
  hide:'Приховати',
  ratings:'Рейтинги',
  team:'Команда',
  details:'Деталі',
  genres:'Жанри',
  reviews:'Відгуки',
  allReviews:'Усі відгуки',
  cast:'Каст',
  directors:'Режисери та сценаристи',
  budget:'Бюджет',
  studios:'студії',
  countries:'Країни',
  originalLanguage:'оригінальні мови',
  speakLanguage:'розмовні мови',
  similarSerials:'Схожі серіали',
  similarFilms:'Схожі фільми',
  homePage:'Домашня сторінка',
  seasons:'Сезони',
  episodes:'Епізоди',
  asKnownAs:'Також відомий/відома як',
  birthday:'Дата народження',
  birthdayPlace:'Місце народження',
  biography:'Біографія',
  rename:'Перейменувати',
  areYouSure:'Ви впевнені?',
  deleteWatchList:'Видалити список',
  noCancel:'Ні,відмінити',
  deleting:'Видалення...',
  yesDelete:'Так, видалити',
  success:'Успішно!',
  chooseFavoriteActors:'Оберіть улюблених акторів',
  chooseFavoriteGenres:'Оберіть улюблені жанри',
  recentActivity:'Остання активність',
  exit:'Вихід',
  subscribersNotFound:'Підписників немає',
  subscriptionsNotFound:'Підписок немає',
  filmsNotFound:'Фільмів не знайдено',
  subscribers:'Підписники',
  subscriptions:'Підписки',
  lists:"Списки",
  newList:'Новий список',
  favorites: 'Улюблені',
  notifications:'Сповіщення',
  sortBy:"Сорторувати за",
  asc:'За зростанням',
  desc:'За спаданням',
  ratingHighest:'Рейтинг Найвищий',
  ratingLowest:'Рейтинг Найнищий',
  all:'Усі',
  successReg:'Реєстрація успішна',
  successAddList:'Список створено?',
  subscriber:'Підписка',
  subscribe:'Підписатись'
}
